apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-federation
  namespace: #MYNS#
data:
  rabbitmq.conf: |
    federation-upstream my-upstream {
      uri: "amqp://guest:guest@rabbitmq.#OTHERNS#.svc.cluster.local";
    }
    federation-upstream-set my-upstream-set {
      upstreams: [my-upstream];
    }
    policies = [
      { vhost: "/", name: "federation-policy", pattern: ".*", definition: { "federation-upstream-set": "my-upstream-set" }, priority: 0 }
    ]

