apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: #MYNS#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbitmq-role-binding
  namespace: #MYNS#
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: #MYNS#
roleRef:
  kind: Role
  name: rabbitmq-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rabbitmq-role
  namespace: #MYNS#
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

