apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_federation,rabbitmq_federation_management,peer_discovery_backend,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.node_cleanup.interval = 10
    cluster_formation.node_cleanup.only_log_warning = true
    cluster_partition_handling = autoheal
    loopback_users.guest = false
    management.load_definitions = /etc/rabbitmq/definitions.json
  definitions.json: |
    {
      "vhosts": [{"name": "/"}],
      "policies": [
        {
          "vhost": "/",
          "name": "ha-all",
          "pattern": ".*",
          "definition": {
            "ha-mode": "all"
          }
        }
      ]
    }

