apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-federation
data:
  rabbitmq.conf: |
    federation-upstream my-upstream {
      uri: "amqp://user:password@rabbitmq.dc2.svc.cluster.local";
    }
    federation-upstream-set my-upstream-set {
      upstreams: [my-upstream];
    }
    policies = [
      { vhost: "/", name: "federation-policy", pattern: ".*", definition: { "federation-upstream-set": "my-upstream-set" }, priority: 0 }
    ]

